### ISSUE TITLE
远程读取class ID访问拒绝

### ISSUE THREAD

**Issue by Tibalt** [hrg-hgzy/OPC_DA#1]
**问题描述**
使用CLIENT功能块读取OPC DA server数据时出错，无法正常获取数据。

**重现方法**
1.首先确定使用opc expert连接远程服务器，读取数据成功，确认OPC da相关配置没有问题；
2.运行可执行文件forte;
3.使用4diac打开opc client项目；
4.配置ID:opc[192.168.103.211:Matrikon.OPC.Simulation:2000:0.0:Random.Int2:Random.Int1];
5.使用IDE deploy并watch数据变化和报错信息；

**预期结果**
可以正常读取到ID中配置的Random.Int1的数据，这个数据是随机变化的。

**环境 (请填写以下资料):**
 - 操作系统: [windows10  10.0.18363]
 - 文件名 [ forte.exe]
 - 版本 [http://192.168.103.237/zhaoxin/forte/tree/1.13.x_feature---e52779b3]
 - 文件名 [RAWMILLOPC]
 - 版本 [http://192.168.103.237/4diac/4diac-demo---63a00f8f]

**其他**
debug时可以看到出错打印信息如下：
```
INFO:T#21925089358: Cwin32SocketInterface: Opening UDP receiving connection at: 225.0.0.1:61498
INFO:T#21925420158: CMin32SocketInterface: Opening UDP receiving connection at: 225.0.0.1:61497
Loaded 'c: \windows \SysWOW64imsv1_e.dll'.
Loaded 'C: lwindows\SysWOw64\bcrypt.dll'.
Loaded "c: \windows ilSysWOw64\NtlmShared.dll".Loaded 'c: \windows \SyswOw64\cryptdll.dll".
Loaded "C: lwindowslSysWOW64\clbcatq.dll'.
onecore(comNcombase ldcomrem(resolver .cxx(2279)/combase.d11!7A805EF: (caller:77AFDC)ReturmHr(1) tid(2a5c)84154 没有注册类
onecorelcom (combase ldcomremresolver.cxx(2483)(combase.d1!77A7FOFD: (caller:77A813E1)ReturmHr(2) tid(2a5c) 804154没有注册类
Exception thrown at x76E546D2 in forte.exe: Nicrosoft CH exception:OPCException at memory location 0xe2DFF450.
DEBUG: T#21955178958: copcComLayer: :closeConnection()
INFO: T#21977752958: Connection established by client
```

**Comment by Tibalt** [comment]
能确定同一款软件，在任何windows（win 10， window server 等）操作系统的注册表中的clsid都一样么？

**Comment by Tibalt** [comment]
regconnectregistry，regopenkeyex这两个函数后边有可能加w和a，具体参考
[https://stackoverflow.com/questions/49073941/how-to-read-windows-registry-data-on-remote-machine-using-java](链接)

其实简单说，不要加a也不要加w，让api自己选择字符集。

**Comment by Tibalt** [comment]
> 能确定同一款软件，在任何windows（win 10， window server 等）操作系统的注册表中的clsid都一样么？

@rockysroll 可以在官方文档中了解一下注册表clsid是什么意思，然后推断一下是不是clsid不会变。如果我们推断不会变，要将clsid做成动态可配的。

**Comment by Tibalt** [comment]
> > 能确定同一款软件，在任何windows（win 10， window server 等）操作系统的注册表中的clsid都一样么？
> 
> @rockysroll 可以在官方文档中了解一下注册表clsid是什么意思，然后推断一下是不是clsid不会变。如果我们推断不会变，要将clsid做成动态可配的。

clsid动态可配不需要在1.01中做。

**Comment by Tibalt** [comment]
我没有找到一个明确的说法，说progid对应的clsid唯一，不过基本上，这是个伪命题。比如，以下链接，就讲了[如何修改progid](https://honeywellprocess-community.force.com/opcsupport/s/article/How-do-I-change-the-program-ID-of-a-Matrikon-OPC-Server)

另外，[progid的定义](https://docs.microsoft.com/en-us/windows/win32/com/-progid--key)，简单一句话```The format of a ProgID is  <Program>.<Component>.<Version>```

最后，[一个帖子](https://stackoverflow.com/questions/19404166/how-to-know-an-opc-server-clsid)说明了如何拿到opc server的clsid。我感觉其中比较靠谱的方式是通过[opc enum](https://stackoverflow.com/a/29688277/14889996)，也就是说当opc server 和local machine都有opc enum的时候，这种方式是可以的。我感觉opc expert就是这种方式。可以试一下。

**Comment by rockysroll** [comment]
添加逻辑读取本地配置文件获取classid，fix in http://192.168.103.237/iiot/opc-client.git 2ae69823
