### ISSUE TITLE
与wincc OPC server通讯时forte抛出未处理异常

### ISSUE THREAD

**Issue by Tibalt** [hrg-hgzy/OPC_DA#2]
**Describe the bug**
与wincc OPC server通讯时forte抛出未处理异常

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
在青州使用的方案是，在收到数据判断数据类型时捕捉异常并且不做处理。

**Comment by rockysroll** [comment]
在opc server itme 的值中输入字符串可以重现这个bug。opc 模块会根据根据输出管脚连接指向的数据类型处理数据，不连线不处理数据。

**Comment by rockysroll** [comment]
修改源码添加捕获异常时的打印信息
![image](https://user-images.githubusercontent.com/28127698/114864576-bf921d00-9e23-11eb-9552-64ecbd82c070.png)

重新部署到现场环境测试情况
![image](https://user-images.githubusercontent.com/28127698/114864525-ac7f4d00-9e23-11eb-88b8-882a248c377d.png)

目前发现的规律是一般都是在程序刚启动时出问题，程序运行过程中不会有问题

**Comment by rockysroll** [comment]
通过try catch 的方式提前处理未定义的数据类型，fix in http://192.168.103.237/zhaoxin/forte.git  d6f33e52  branch:1.13.x_feature
